import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#fff',
        alignContent: 'center',
    },
    nav: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.2,
        shadowRadius: 1.5,
    },
    profil: {
        margin: 8,
        padding: 10,
        shadowColor: '#000',
        shadowOffset: { width: 2, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 2,
    },
    name: {
        color: "white",
        fontSize: 25,
        fontWeight: '800',
        marginTop: 10,
    },
    info: {
        fontWeight: 'bold',
        color: "white",
        fontSize: 14,
        marginTop: 5,
        marginLeft: 2,
    },
    hr: {
        justifyContent: 'space-between',
        alignItems: 'center',
        borderBottomWidth: 1,
        padding: 5,
        flexDirection: 'row',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.2,
        shadowRadius: 1.5,
    },
    main: {
        margin: 10,
        justifyContent: 'center',
        flexDirection: 'row',
        flexWrap: 'wrap',
    },
    menu: {
        margin: 15,
        height: 130,
        width: 130,
    },
    modalview: {
        width: '100%',
        height: '100%',
        backgroundColor: 'rgba(0, 0, 0, 0.4)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalmenu: {
        borderRadius: 9,
        justifyContent: 'center',
        alignItems: 'center',
        width: '85%',
        height: '75%',
        gap: 20,
    },
    valuename: {
        fontSize: 28,
        fontWeight: 'bold',
        color: 'white',
    },
    value: {
        flexDirection: 'row',
        borderRadius: 4,
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: 'white',
        width: '70%',
        height: '5.5%',
    },
    sec: {
        backgroundColor: '#eee',
        marginBottom: 2,
        borderRadius: 4,
        paddingTop: 5,
        paddingLeft: 70,
        paddingBottom: 5,
        paddingRight: 70,
    },
    logincontainer: {
        backgroundColor: '#fff',
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    head: {
        fontSize: 50,
        fontWeight: 'bold',
        marginBottom: 25,
    },
    loginput: {
        backgroundColor: '#eee',
        borderColor: '#00e2cd',
        borderWidth: 2,
        borderRadius: 7,
        paddingLeft: 20,
        margin: 5,
        width: '75%',
        height: '5%',
    },
    button: {
        backgroundColor: '#00e2cd',
        justifyContent: 'center',
        marginTop: 10,
        marginBottom: 10,
        borderRadius: 7,
        width: '37%',
        height: 40,
    },
    buttontext: {
        fontWeight: 'bold',
        textAlign: 'center',
    },
    signup: {
        backgroundColor: '#fff',
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
});
